/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package braindrainlearninggame;
import java.util.Random;
import javax.swing.*;

/**
 *
 * @author luisp
 */
public class BrainDrainLearningGame extends javax.swing.JFrame implements Dice{
    Questions questions = new Questions();
    Answers answers = new Answers();
    /**
     * Creates new form BrainDrainLearningGame
     */
    public BrainDrainLearningGame() {
        initComponents();
        txtP1Name.setBackground(new java.awt.Color(0,0,0,1));
        setSize(765, 408);
        lblP2EnterName.setVisible(false);
        txtP2Name.setVisible(false);
        btnP2Ok.setVisible(false);
        lblP1.setVisible(false);
        lblP2.setVisible(false);
        lblTile1.setVisible(false);
        lblTile2.setVisible(false);
        lblTile3.setVisible(false);
        lblTile4.setVisible(false);
        lblTile5.setVisible(false);       
        lblPlayerTurn.setVisible(false);
        btnDice.setVisible(false);
        
        
        
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnP2Ok = new javax.swing.JButton();
        btnP1Ok = new javax.swing.JButton();
        txtP2Name = new javax.swing.JTextField();
        txtP1Name = new javax.swing.JTextField();
        lblP2EnterName = new javax.swing.JLabel();
        lblP1EnterName = new javax.swing.JLabel();
        lblTile100 = new javax.swing.JLabel();
        lblTile99 = new javax.swing.JLabel();
        lblTile98 = new javax.swing.JLabel();
        lblTile97 = new javax.swing.JLabel();
        lblTile96 = new javax.swing.JLabel();
        lblTile95 = new javax.swing.JLabel();
        lblTile94 = new javax.swing.JLabel();
        lblTile93 = new javax.swing.JLabel();
        lblTile92 = new javax.swing.JLabel();
        lblTile91 = new javax.swing.JLabel();
        lblTile90 = new javax.swing.JLabel();
        lblTile89 = new javax.swing.JLabel();
        lblTile88 = new javax.swing.JLabel();
        lblTile87 = new javax.swing.JLabel();
        lblTile86 = new javax.swing.JLabel();
        lblTile85 = new javax.swing.JLabel();
        lblTile84 = new javax.swing.JLabel();
        lblTile83 = new javax.swing.JLabel();
        lblTile82 = new javax.swing.JLabel();
        lblTile81 = new javax.swing.JLabel();
        lblTile80 = new javax.swing.JLabel();
        lblTile79 = new javax.swing.JLabel();
        lblTile78 = new javax.swing.JLabel();
        lblTile77 = new javax.swing.JLabel();
        lblTile76 = new javax.swing.JLabel();
        lblTile75 = new javax.swing.JLabel();
        lblTile74 = new javax.swing.JLabel();
        lblTile73 = new javax.swing.JLabel();
        lblTile72 = new javax.swing.JLabel();
        lblTile71 = new javax.swing.JLabel();
        lblTile70 = new javax.swing.JLabel();
        lblTile69 = new javax.swing.JLabel();
        lblTile68 = new javax.swing.JLabel();
        lblTile67 = new javax.swing.JLabel();
        lblTile66 = new javax.swing.JLabel();
        lblTile65 = new javax.swing.JLabel();
        lblTile64 = new javax.swing.JLabel();
        lblTile63 = new javax.swing.JLabel();
        lblTile62 = new javax.swing.JLabel();
        lblTile61 = new javax.swing.JLabel();
        lblTile60 = new javax.swing.JLabel();
        lblTile59 = new javax.swing.JLabel();
        lblTile58 = new javax.swing.JLabel();
        lblTile57 = new javax.swing.JLabel();
        lblTile56 = new javax.swing.JLabel();
        lblTile55 = new javax.swing.JLabel();
        lblTile54 = new javax.swing.JLabel();
        lblTile53 = new javax.swing.JLabel();
        lblTile52 = new javax.swing.JLabel();
        lblTile51 = new javax.swing.JLabel();
        lblTile50 = new javax.swing.JLabel();
        lblTile49 = new javax.swing.JLabel();
        lblTile48 = new javax.swing.JLabel();
        lblTile47 = new javax.swing.JLabel();
        lblTile46 = new javax.swing.JLabel();
        lblTile45 = new javax.swing.JLabel();
        lblTile44 = new javax.swing.JLabel();
        lblTile43 = new javax.swing.JLabel();
        lblTile42 = new javax.swing.JLabel();
        lblTile41 = new javax.swing.JLabel();
        lblTile40 = new javax.swing.JLabel();
        lblTile39 = new javax.swing.JLabel();
        lblTile38 = new javax.swing.JLabel();
        lblTile37 = new javax.swing.JLabel();
        lblTile36 = new javax.swing.JLabel();
        lblTile35 = new javax.swing.JLabel();
        lblTile34 = new javax.swing.JLabel();
        lblTile33 = new javax.swing.JLabel();
        lblTile32 = new javax.swing.JLabel();
        lblTile31 = new javax.swing.JLabel();
        lblTile30 = new javax.swing.JLabel();
        lblTile29 = new javax.swing.JLabel();
        lblTile28 = new javax.swing.JLabel();
        lblTile27 = new javax.swing.JLabel();
        lblTile26 = new javax.swing.JLabel();
        lblTile25 = new javax.swing.JLabel();
        lblTile24 = new javax.swing.JLabel();
        lblTile23 = new javax.swing.JLabel();
        lblTile22 = new javax.swing.JLabel();
        lblTile21 = new javax.swing.JLabel();
        lblTile20 = new javax.swing.JLabel();
        lblTile19 = new javax.swing.JLabel();
        lblTile18 = new javax.swing.JLabel();
        lblTile17 = new javax.swing.JLabel();
        lblTile16 = new javax.swing.JLabel();
        lblTile15 = new javax.swing.JLabel();
        lblTile14 = new javax.swing.JLabel();
        lblTile13 = new javax.swing.JLabel();
        lblTile12 = new javax.swing.JLabel();
        lblTile11 = new javax.swing.JLabel();
        lblTile10 = new javax.swing.JLabel();
        lblTile9 = new javax.swing.JLabel();
        lblTile8 = new javax.swing.JLabel();
        lblTile7 = new javax.swing.JLabel();
        lblTile6 = new javax.swing.JLabel();
        lblTile5 = new javax.swing.JLabel();
        lblTile4 = new javax.swing.JLabel();
        lblTile3 = new javax.swing.JLabel();
        lblTile2 = new javax.swing.JLabel();
        lblTile1 = new javax.swing.JLabel();
        lblP2 = new javax.swing.JLabel();
        lblP1 = new javax.swing.JLabel();
        btnDice = new javax.swing.JButton();
        lblPlayerTurn = new javax.swing.JLabel();
        lblDiceResult = new javax.swing.JLabel();
        lblBoard = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(800, 340));
        getContentPane().setLayout(null);

        btnP2Ok.setIcon(new javax.swing.ImageIcon(getClass().getResource("/braindrainlearninggame/Images/Player1Ok.png"))); // NOI18N
        btnP2Ok.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnP2Ok.setBorderPainted(false);
        btnP2Ok.setContentAreaFilled(false);
        btnP2Ok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnP2OkActionPerformed(evt);
            }
        });
        getContentPane().add(btnP2Ok);
        btnP2Ok.setBounds(520, 150, 80, 30);

        btnP1Ok.setIcon(new javax.swing.ImageIcon(getClass().getResource("/braindrainlearninggame/Images/Player1Ok.png"))); // NOI18N
        btnP1Ok.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnP1Ok.setBorderPainted(false);
        btnP1Ok.setContentAreaFilled(false);
        btnP1Ok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnP1OkActionPerformed(evt);
            }
        });
        getContentPane().add(btnP1Ok);
        btnP1Ok.setBounds(520, 60, 80, 30);

        txtP2Name.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        txtP2Name.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        txtP2Name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtP2NameActionPerformed(evt);
            }
        });
        getContentPane().add(txtP2Name);
        txtP2Name.setBounds(550, 130, 90, 20);

        txtP1Name.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        txtP1Name.setForeground(new java.awt.Color(255, 255, 255));
        txtP1Name.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        txtP1Name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtP1NameActionPerformed(evt);
            }
        });
        getContentPane().add(txtP1Name);
        txtP1Name.setBounds(550, 40, 90, 26);

        lblP2EnterName.setIcon(new javax.swing.ImageIcon(getClass().getResource("/braindrainlearninggame/Images/EnterPlayer2Name.png"))); // NOI18N
        getContentPane().add(lblP2EnterName);
        lblP2EnterName.setBounds(470, 100, 180, 80);

        lblP1EnterName.setIcon(new javax.swing.ImageIcon(getClass().getResource("/braindrainlearninggame/Images/EnterPlayer1Name.png"))); // NOI18N
        getContentPane().add(lblP1EnterName);
        lblP1EnterName.setBounds(470, 10, 180, 80);
        getContentPane().add(lblTile100);
        lblTile100.setBounds(99, 14, 29, 29);
        getContentPane().add(lblTile99);
        lblTile99.setBounds(168, 14, 30, 30);
        getContentPane().add(lblTile98);
        lblTile98.setBounds(203, 16, 29, 29);
        getContentPane().add(lblTile97);
        lblTile97.setBounds(237, 14, 30, 30);
        getContentPane().add(lblTile96);
        lblTile96.setBounds(270, 16, 29, 29);
        getContentPane().add(lblTile95);
        lblTile95.setBounds(307, 14, 30, 30);
        getContentPane().add(lblTile94);
        lblTile94.setBounds(340, 16, 29, 29);
        getContentPane().add(lblTile93);
        lblTile93.setBounds(377, 14, 30, 30);
        getContentPane().add(lblTile92);
        lblTile92.setBounds(410, 16, 29, 29);
        getContentPane().add(lblTile91);
        lblTile91.setBounds(134, 16, 29, 29);
        getContentPane().add(lblTile90);
        lblTile90.setBounds(410, 48, 30, 30);
        getContentPane().add(lblTile89);
        lblTile89.setBounds(377, 48, 29, 29);
        getContentPane().add(lblTile88);
        lblTile88.setBounds(342, 48, 30, 30);
        getContentPane().add(lblTile87);
        lblTile87.setBounds(309, 48, 29, 29);
        getContentPane().add(lblTile86);
        lblTile86.setBounds(273, 48, 30, 30);
        getContentPane().add(lblTile85);
        lblTile85.setBounds(239, 48, 29, 29);
        getContentPane().add(lblTile84);
        lblTile84.setBounds(203, 48, 30, 30);
        getContentPane().add(lblTile83);
        lblTile83.setBounds(170, 48, 29, 29);
        getContentPane().add(lblTile82);
        lblTile82.setBounds(133, 48, 30, 30);
        getContentPane().add(lblTile81);
        lblTile81.setBounds(100, 48, 29, 29);
        getContentPane().add(lblTile80);
        lblTile80.setBounds(99, 80, 30, 30);
        getContentPane().add(lblTile79);
        lblTile79.setBounds(134, 83, 29, 29);
        getContentPane().add(lblTile78);
        lblTile78.setBounds(168, 80, 30, 30);
        getContentPane().add(lblTile77);
        lblTile77.setBounds(203, 83, 29, 29);
        getContentPane().add(lblTile76);
        lblTile76.setBounds(237, 80, 30, 30);
        getContentPane().add(lblTile75);
        lblTile75.setBounds(270, 83, 29, 29);
        getContentPane().add(lblTile74);
        lblTile74.setBounds(307, 80, 30, 30);
        getContentPane().add(lblTile73);
        lblTile73.setBounds(340, 83, 29, 29);
        getContentPane().add(lblTile72);
        lblTile72.setBounds(377, 80, 30, 30);
        getContentPane().add(lblTile71);
        lblTile71.setBounds(410, 83, 29, 29);
        getContentPane().add(lblTile70);
        lblTile70.setBounds(411, 117, 30, 30);
        getContentPane().add(lblTile69);
        lblTile69.setBounds(377, 118, 29, 29);
        getContentPane().add(lblTile68);
        lblTile68.setBounds(342, 117, 30, 30);
        getContentPane().add(lblTile67);
        lblTile67.setBounds(309, 118, 29, 29);
        getContentPane().add(lblTile66);
        lblTile66.setBounds(273, 117, 30, 30);
        getContentPane().add(lblTile65);
        lblTile65.setBounds(239, 118, 29, 29);
        getContentPane().add(lblTile64);
        lblTile64.setBounds(203, 117, 30, 30);
        getContentPane().add(lblTile63);
        lblTile63.setBounds(170, 118, 29, 29);
        getContentPane().add(lblTile62);
        lblTile62.setBounds(133, 117, 30, 30);
        getContentPane().add(lblTile61);
        lblTile61.setBounds(100, 118, 29, 29);
        getContentPane().add(lblTile60);
        lblTile60.setBounds(99, 153, 30, 30);
        getContentPane().add(lblTile59);
        lblTile59.setBounds(134, 153, 29, 29);
        getContentPane().add(lblTile58);
        lblTile58.setBounds(168, 153, 30, 30);
        getContentPane().add(lblTile57);
        lblTile57.setBounds(203, 153, 29, 29);
        getContentPane().add(lblTile56);
        lblTile56.setBounds(237, 153, 30, 30);
        getContentPane().add(lblTile55);
        lblTile55.setBounds(270, 153, 29, 29);
        getContentPane().add(lblTile54);
        lblTile54.setBounds(307, 153, 30, 30);
        getContentPane().add(lblTile53);
        lblTile53.setBounds(340, 153, 29, 29);
        getContentPane().add(lblTile52);
        lblTile52.setBounds(377, 153, 30, 30);
        getContentPane().add(lblTile51);
        lblTile51.setBounds(410, 153, 29, 29);
        getContentPane().add(lblTile50);
        lblTile50.setBounds(411, 187, 30, 30);
        getContentPane().add(lblTile49);
        lblTile49.setBounds(377, 188, 29, 29);
        getContentPane().add(lblTile48);
        lblTile48.setBounds(342, 187, 30, 30);
        getContentPane().add(lblTile47);
        lblTile47.setBounds(309, 188, 29, 29);
        getContentPane().add(lblTile46);
        lblTile46.setBounds(273, 187, 30, 30);
        getContentPane().add(lblTile45);
        lblTile45.setBounds(239, 188, 29, 29);
        getContentPane().add(lblTile44);
        lblTile44.setBounds(203, 187, 30, 30);
        getContentPane().add(lblTile43);
        lblTile43.setBounds(170, 188, 29, 29);
        getContentPane().add(lblTile42);
        lblTile42.setBounds(133, 187, 30, 30);
        getContentPane().add(lblTile41);
        lblTile41.setBounds(100, 188, 29, 29);
        getContentPane().add(lblTile40);
        lblTile40.setBounds(99, 221, 30, 30);
        getContentPane().add(lblTile39);
        lblTile39.setBounds(134, 222, 29, 29);
        getContentPane().add(lblTile38);
        lblTile38.setBounds(168, 221, 30, 30);
        getContentPane().add(lblTile37);
        lblTile37.setBounds(203, 222, 29, 29);
        getContentPane().add(lblTile36);
        lblTile36.setBounds(237, 221, 30, 30);
        getContentPane().add(lblTile35);
        lblTile35.setBounds(270, 222, 29, 29);
        getContentPane().add(lblTile34);
        lblTile34.setBounds(307, 221, 30, 30);
        getContentPane().add(lblTile33);
        lblTile33.setBounds(340, 222, 29, 29);
        getContentPane().add(lblTile32);
        lblTile32.setBounds(377, 221, 30, 30);
        getContentPane().add(lblTile31);
        lblTile31.setBounds(410, 222, 29, 29);
        getContentPane().add(lblTile30);
        lblTile30.setBounds(411, 257, 30, 30);
        getContentPane().add(lblTile29);
        lblTile29.setBounds(377, 258, 29, 29);
        getContentPane().add(lblTile28);
        lblTile28.setBounds(342, 257, 30, 30);
        getContentPane().add(lblTile27);
        lblTile27.setBounds(309, 258, 29, 29);
        getContentPane().add(lblTile26);
        lblTile26.setBounds(273, 257, 30, 30);
        getContentPane().add(lblTile25);
        lblTile25.setBounds(239, 258, 29, 29);
        getContentPane().add(lblTile24);
        lblTile24.setBounds(203, 257, 30, 30);
        getContentPane().add(lblTile23);
        lblTile23.setBounds(170, 258, 29, 29);
        getContentPane().add(lblTile22);
        lblTile22.setBounds(133, 257, 30, 30);
        getContentPane().add(lblTile21);
        lblTile21.setBounds(100, 258, 29, 29);
        getContentPane().add(lblTile20);
        lblTile20.setBounds(99, 291, 30, 30);
        getContentPane().add(lblTile19);
        lblTile19.setBounds(134, 292, 29, 29);
        getContentPane().add(lblTile18);
        lblTile18.setBounds(168, 291, 30, 30);
        getContentPane().add(lblTile17);
        lblTile17.setBounds(203, 292, 29, 29);
        getContentPane().add(lblTile16);
        lblTile16.setBounds(238, 291, 30, 30);
        getContentPane().add(lblTile15);
        lblTile15.setBounds(273, 292, 29, 29);
        getContentPane().add(lblTile14);
        lblTile14.setBounds(307, 291, 30, 30);
        getContentPane().add(lblTile13);
        lblTile13.setBounds(340, 292, 29, 29);
        getContentPane().add(lblTile12);
        lblTile12.setBounds(377, 291, 30, 30);
        getContentPane().add(lblTile11);
        lblTile11.setBounds(411, 292, 29, 29);
        getContentPane().add(lblTile10);
        lblTile10.setBounds(411, 326, 30, 30);
        getContentPane().add(lblTile9);
        lblTile9.setBounds(378, 328, 29, 29);
        getContentPane().add(lblTile8);
        lblTile8.setBounds(342, 326, 30, 30);
        getContentPane().add(lblTile7);
        lblTile7.setBounds(308, 328, 29, 29);
        getContentPane().add(lblTile6);
        lblTile6.setBounds(273, 326, 30, 30);
        getContentPane().add(lblTile5);
        lblTile5.setBounds(239, 328, 29, 29);
        getContentPane().add(lblTile4);
        lblTile4.setBounds(203, 326, 30, 30);
        getContentPane().add(lblTile3);
        lblTile3.setBounds(170, 328, 29, 29);
        getContentPane().add(lblTile2);
        lblTile2.setBounds(133, 326, 30, 30);
        getContentPane().add(lblTile1);
        lblTile1.setBounds(100, 326, 28, 28);

        lblP2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/braindrainlearninggame/Images/Player 2.png"))); // NOI18N
        getContentPane().add(lblP2);
        lblP2.setBounds(60, 320, 28, 28);

        lblP1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/braindrainlearninggame/Images/Player 1.png"))); // NOI18N
        getContentPane().add(lblP1);
        lblP1.setBounds(20, 310, 28, 28);

        btnDice.setIcon(new javax.swing.ImageIcon(getClass().getResource("/braindrainlearninggame/Images/Dice.png"))); // NOI18N
        btnDice.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnDice.setBorderPainted(false);
        btnDice.setContentAreaFilled(false);
        btnDice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDiceActionPerformed(evt);
            }
        });
        getContentPane().add(btnDice);
        btnDice.setBounds(490, 300, 50, 50);
        getContentPane().add(lblPlayerTurn);
        lblPlayerTurn.setBounds(490, 260, 120, 30);
        getContentPane().add(lblDiceResult);
        lblDiceResult.setBounds(570, 300, 60, 50);

        lblBoard.setDisplayedMnemonic('B');
        lblBoard.setIcon(new javax.swing.ImageIcon(getClass().getResource("/braindrainlearninggame/Images/Game Play.png"))); // NOI18N
        lblBoard.setMaximumSize(new java.awt.Dimension(749, 369));
        lblBoard.setMinimumSize(new java.awt.Dimension(749, 369));
        lblBoard.setPreferredSize(new java.awt.Dimension(749, 369));
        getContentPane().add(lblBoard);
        lblBoard.setBounds(0, 0, 750, 370);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void txtP1NameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtP1NameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtP1NameActionPerformed

    private void btnP1OkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnP1OkActionPerformed
        // TODO add your handling code here:
        if(txtP1Name.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "This field is required", "Required Name", JOptionPane.INFORMATION_MESSAGE);
        }
        else{
            lblP1EnterName.setVisible(false);
            txtP1Name.setVisible(false);
            btnP1Ok.setVisible(false);
            lblP2EnterName.setVisible(true);
            txtP2Name.setVisible(true);
            btnP2Ok.setVisible(true);
            
        }
        //lblTile1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/braindrainlearninggame/Images/Player 2.png"))); 
    }//GEN-LAST:event_btnP1OkActionPerformed

    private void txtP2NameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtP2NameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtP2NameActionPerformed

    private void btnP2OkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnP2OkActionPerformed
        // TODO add your handling code here:
        if(txtP2Name.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "This field is required", "Required Name", JOptionPane.INFORMATION_MESSAGE);
        }
        else{  
            lblP2EnterName.setVisible(false);
            txtP2Name.setVisible(false);
            btnP2Ok.setVisible(false);
            lblP1.setVisible(true);
            lblP2.setVisible(true);
            lblTile1.setVisible(true);
            lblTile2.setVisible(true);
            lblTile3.setVisible(true);
            lblTile4.setVisible(true);
            lblTile5.setVisible(true);
          
            lblPlayerTurn.setVisible(true);
            btnDice.setVisible(true);
        }
    
        
    }//GEN-LAST:event_btnP2OkActionPerformed
    int turn=0;
    int player1Pos = 0;
    int player2Pos = 0;
    private void btnDiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDiceActionPerformed
        
        if(turn % 2 == 0){
            int diceResult = roll();
            player1Pos += diceResult;
            lblDiceResult.setText(""+diceResult);
            /*movePlayer(lblP1, player1Pos);*/
            lblPlayerTurn.setText(txtP1Name.getText() + "'s Turn");
            String question = questions.getQuestionByIndex(player1Pos);
            String answer = JOptionPane.showInputDialog(null, question);
                /*if (userAnswer == null || !userAnswer.equalsIgnoreCase(answers.checkAnswer(player1Pos, userAnswer))) {*/
                if (answer == null || !answers.checkAnswer(player1Pos, answer)) {
                    player1Pos -= diceResult;
                    JOptionPane.showMessageDialog(null, "Incorrect answer! You cannot move.", "Warning", JOptionPane.INFORMATION_MESSAGE);
                } else {
                    movePlayer(lblP1, player1Pos);
                }
            turn++;
         }else{
            int diceResult2 = roll();
            player2Pos += diceResult2;
            lblDiceResult.setText(""+diceResult2);
            /*movePlayer(lblP2, player2Pos);*/
            lblPlayerTurn.setText(txtP2Name.getText() + "'s Turn");
            String question = questions.getQuestionByIndex(player2Pos);
            String answer = JOptionPane.showInputDialog(null, question);
                if (answer == null || !answers.checkAnswer(player2Pos, answer)) {
                    player2Pos -= diceResult2;
                    JOptionPane.showMessageDialog(null, "Incorrect answer! You cannot move.");
                } else {
                    movePlayer(lblP2, player2Pos);
                }
            turn++;
        }
    }//GEN-LAST:event_btnDiceActionPerformed
    
    private void movePlayer(javax.swing.JLabel playerLabel, int position) {
    // Calculate the x and y coordinates of the new position on the board
    int x = 99 + ((position - 1) % 10) * 34;
    int y = 326 - ((position - 1) / 10) * 34;
    
    // Set the new position of the player icon
    playerLabel.setBounds(x, y, 28, 28);
}
    @Override
    public int roll(){
        Random random = new Random();
        int diceResult = random.nextInt(6) + 1; 
        
        return diceResult;
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BrainDrainLearningGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BrainDrainLearningGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BrainDrainLearningGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BrainDrainLearningGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            
            public void run() {
                new BrainDrainLearningGame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDice;
    private javax.swing.JButton btnP1Ok;
    private javax.swing.JButton btnP2Ok;
    private javax.swing.JLabel lblBoard;
    private javax.swing.JLabel lblDiceResult;
    private javax.swing.JLabel lblP1;
    private javax.swing.JLabel lblP1EnterName;
    private javax.swing.JLabel lblP2;
    private javax.swing.JLabel lblP2EnterName;
    private javax.swing.JLabel lblPlayerTurn;
    private javax.swing.JLabel lblTile1;
    private javax.swing.JLabel lblTile10;
    private javax.swing.JLabel lblTile100;
    private javax.swing.JLabel lblTile11;
    private javax.swing.JLabel lblTile12;
    private javax.swing.JLabel lblTile13;
    private javax.swing.JLabel lblTile14;
    private javax.swing.JLabel lblTile15;
    private javax.swing.JLabel lblTile16;
    private javax.swing.JLabel lblTile17;
    private javax.swing.JLabel lblTile18;
    private javax.swing.JLabel lblTile19;
    private javax.swing.JLabel lblTile2;
    private javax.swing.JLabel lblTile20;
    private javax.swing.JLabel lblTile21;
    private javax.swing.JLabel lblTile22;
    private javax.swing.JLabel lblTile23;
    private javax.swing.JLabel lblTile24;
    private javax.swing.JLabel lblTile25;
    private javax.swing.JLabel lblTile26;
    private javax.swing.JLabel lblTile27;
    private javax.swing.JLabel lblTile28;
    private javax.swing.JLabel lblTile29;
    private javax.swing.JLabel lblTile3;
    private javax.swing.JLabel lblTile30;
    private javax.swing.JLabel lblTile31;
    private javax.swing.JLabel lblTile32;
    private javax.swing.JLabel lblTile33;
    private javax.swing.JLabel lblTile34;
    private javax.swing.JLabel lblTile35;
    private javax.swing.JLabel lblTile36;
    private javax.swing.JLabel lblTile37;
    private javax.swing.JLabel lblTile38;
    private javax.swing.JLabel lblTile39;
    private javax.swing.JLabel lblTile4;
    private javax.swing.JLabel lblTile40;
    private javax.swing.JLabel lblTile41;
    private javax.swing.JLabel lblTile42;
    private javax.swing.JLabel lblTile43;
    private javax.swing.JLabel lblTile44;
    private javax.swing.JLabel lblTile45;
    private javax.swing.JLabel lblTile46;
    private javax.swing.JLabel lblTile47;
    private javax.swing.JLabel lblTile48;
    private javax.swing.JLabel lblTile49;
    private javax.swing.JLabel lblTile5;
    private javax.swing.JLabel lblTile50;
    private javax.swing.JLabel lblTile51;
    private javax.swing.JLabel lblTile52;
    private javax.swing.JLabel lblTile53;
    private javax.swing.JLabel lblTile54;
    private javax.swing.JLabel lblTile55;
    private javax.swing.JLabel lblTile56;
    private javax.swing.JLabel lblTile57;
    private javax.swing.JLabel lblTile58;
    private javax.swing.JLabel lblTile59;
    private javax.swing.JLabel lblTile6;
    private javax.swing.JLabel lblTile60;
    private javax.swing.JLabel lblTile61;
    private javax.swing.JLabel lblTile62;
    private javax.swing.JLabel lblTile63;
    private javax.swing.JLabel lblTile64;
    private javax.swing.JLabel lblTile65;
    private javax.swing.JLabel lblTile66;
    private javax.swing.JLabel lblTile67;
    private javax.swing.JLabel lblTile68;
    private javax.swing.JLabel lblTile69;
    private javax.swing.JLabel lblTile7;
    private javax.swing.JLabel lblTile70;
    private javax.swing.JLabel lblTile71;
    private javax.swing.JLabel lblTile72;
    private javax.swing.JLabel lblTile73;
    private javax.swing.JLabel lblTile74;
    private javax.swing.JLabel lblTile75;
    private javax.swing.JLabel lblTile76;
    private javax.swing.JLabel lblTile77;
    private javax.swing.JLabel lblTile78;
    private javax.swing.JLabel lblTile79;
    private javax.swing.JLabel lblTile8;
    private javax.swing.JLabel lblTile80;
    private javax.swing.JLabel lblTile81;
    private javax.swing.JLabel lblTile82;
    private javax.swing.JLabel lblTile83;
    private javax.swing.JLabel lblTile84;
    private javax.swing.JLabel lblTile85;
    private javax.swing.JLabel lblTile86;
    private javax.swing.JLabel lblTile87;
    private javax.swing.JLabel lblTile88;
    private javax.swing.JLabel lblTile89;
    private javax.swing.JLabel lblTile9;
    private javax.swing.JLabel lblTile90;
    private javax.swing.JLabel lblTile91;
    private javax.swing.JLabel lblTile92;
    private javax.swing.JLabel lblTile93;
    private javax.swing.JLabel lblTile94;
    private javax.swing.JLabel lblTile95;
    private javax.swing.JLabel lblTile96;
    private javax.swing.JLabel lblTile97;
    private javax.swing.JLabel lblTile98;
    private javax.swing.JLabel lblTile99;
    private javax.swing.JTextField txtP1Name;
    private javax.swing.JTextField txtP2Name;
    // End of variables declaration//GEN-END:variables
}
